### ISSUE TITLE
Meta language ?

### ISSUE THREAD

**Issue by tst2005** [mingodad/ljs#3]
Hello,

I wonder what is your goal for the ljs project.
* for the fun / experimental ?
* for production ?

IMHO, the Lua syntax is not really sexy at all but I'm using it without problem.
I'm still looking about alternative, like moonscript, etc.

I thought (like your project) to using different language syntaxes to execute on the Lua VM (in fact in the LuaJIT one).

There is some case where the usual way to code is complicated to make abstraction.

For sample,
How to you deal with the first array's index is 1 in Lua VS 0 in JS ?

```lua
local cars = {"Saab", "Volvo", "BMW"}
print(cars[1]=="Saab")
```
VS
```js
var cars = new Array("Saab", "Volvo", "BMW");
print(vars[0]=="Saab")
```

Regards,

**Comment by mingodad** [comment]
Hello TsT !
My idea is to use it in production.
The case of 1/0 base index is still there LJS/LjsJIT is 1 based index right now, because this way it's easy to port existing Lua code for testing, in fact I'm finishing now Openresty and Torch, this way I can verify that my changes do not make the language buggy.
As a second stage probably a 0 index based version will come to light, I'm thinking how that can be implemented in a way to make easy to have mainly extensions usable on both Lua/LuaJIT and LJS/LjsJIT .
Probably having some macros/inline functions to hide the conversion in C/Lua code:
```
#define LUA_ADJUST_INDEX(x)  ...
...
for(int i=LUA_ADJUST_INDEX(1), last_i = LUA_ADJUST_INDEX(len_of_object); i < last_i; ++i) {...}
```
